version: '3'
services:
  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  manager:
    build:
      context: ./Manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"