version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    env_file:
      mongo.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  manager:
    build:
      context: ./Manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

volumes:
  dbdata6:
